version: 2.1
jobs:
  checkout:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/homepage/frontEnd
    steps:
      - checkout:
        path: ~/homepage
      - run: yarn
      - run: yarn
      - run: yarn build

