version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - add_ssh_keys:
          fingerprints:
            -"74:e6:1a:39:21:ba:d0:3d:0c:98:bc:47:99:55:1a:16"
      - run: ssh-keyscan -p ${HOST_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts
      - run: sudo apt-get install -y rsync
      - run: rsync -avz --omit-dir-times --delete -e "ssh -p ${HOST_PORT}" ./public/ ${USER_NAME}@${HOST_NAME}:/opt/app/public/

workflows:
  version: 2
  build_only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - release
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - release
